### ISSUE TITLE
Can we get this on `npm`

### ISSUE THREAD

**Issue by marnusw** [luwes/selection-polyfill#6]
I see the name `selection-polyfill` is available on `npm` but this package isn't on there. Is there a reason for this, perhaps that it is not actively maintained anymore? If it still is, would you please consider publishing it there?

Are there any alternatives? It seems like the well known shims like [`es5-shim`](https://github.com/es-shims/es5-shim) doesn't cater for this.

**Comment by luwes** [comment]
@marnusw Github projects can be always be installed using this syntax I believe;
`npm install luwes/selection-polyfill` 

There are alternatives but at the time I build this they were very bulky and they're not drop in polyfill's. 
https://github.com/timdown/rangy

**Comment by marnusw** [comment]
*Face palm* of course. I actually knew that, just goes to show how easy it is to get stuck in linear thinking. 

Still, when I was looking for a polyfill I started out with a search on `npm`, so perhaps it's still something to consider? Especially with the descriptive package name still available.

Thanks for creating the polyfill and the quick reply!

**Comment by marnusw** [comment]
Come to think of it, Bower might be the more suitable of the two (if not both) since it will usually be downloaded as a standalone file. Looks like the package name is available there too by the way.
